name: Update README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm install

      - name: Generate README file
        run: node index.js
        env:
          OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}

      - name: Commit and push changes
        run: |
          git config --local user.email "rhshourav02@gmail.com"
          git config --local user.name "rhshourav"
          git add README.md
          git commit -m "Automated README update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
